[package]
name = "db_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.5"
postgres = "0.19.5"
sqlite = "0.31.0"
[dependencies.redis]
version = "*"

